version: '3.9'

services:
  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env # Using the .env file for environment variables
    environment:
      MYSQL_DATABASE: bookdelivery
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
        - bookDeliveryNetwork
